version: '3.8'
services:
  api:
    image: 'coursework-1901321002-storage-app'
    build: .
    command: sh ./commands/${ENTRY_POINT}.entrypoint.sh
    ports:
      - ${SERVER_PORT-3456}:${SERVER_PORT}
    depends_on:
      - db
    volumes:
      - ./src:/src
      - node-modules-mount:/node_modules
      - dist-mount:/dist
    environment:
      - ENV_FILE_PATH
  db:
    image: 'postgres:14.4'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin1234
    ports:
      - '${PG_ADMIN_PORT-5050}:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    logging:
      driver: none
volumes:
  pgadmin:
  node-modules-mount:
  db-data:
  dist-mount:

